
- name: Add required apt PPAs
  become: yes
  ansible.builtin.apt_repository:
    repo: "ppa:{{ item }}"
  with_items: "{{ ubuntu_ppa  }}"

#- name: Upgrade apt packages
#  become: yes
#  apt: 
#    upgrade: yes
#    update_cache: yes
#  when: package_upgrade

- name: Install apt packages
  become: yes
  apt: 
    name: "{{ ubuntu_packages }}"
  when: package_upgrade
