


- name: Update apt cache
  become: yes
  apt: update_cache=yes
  when: package_update

- name: Upgrade apt packages
  become: yes
  apt: upgrade=yes
  when: package_upgrade

- name: Install apt packages
  become: yes
  apt: 
    name: "{{ ubuntu_packages }}"
  when: package_upgrade
