- name: Set up local development environment
  hosts: all
  pre_tasks:
    - name: Import General vars
      ansible.builtin.include_vars: "vars/general.yaml"
    - name: Import vars per OS
      ansible.builtin.include_vars: "{{ lookup('first_found', params)  }}"
      vars:
        params:
          files:
            - '{{ansible_distribution}}.yaml'
            - '{{ansible_os_family}}.yaml'
          paths:
            - 'vars'        

    - name: Pre-flight Checks | Variables
      assert: 
        that:
          - dotfiles_home is defined
  roles:
    # Tag each role so that we can select individual roles to run with ansible-playbook --tags
    - {role: package_manager, tags: ['package_manager', 'bootstrap']}
    - {role: dotfiles, tags: ['bootstrap']}
    - {role: fonts, tags: ['fonts']}
    - {role: git, tags: ['git']}
    - {role: zsh, tags: ['zsh', 'bootstrap']}
    - {role: python, tags: ['python']}
    - {role: vim, tags: ['vim']}
    - {role: tmux, tags: ['tmux']}
    #- {role: kubernetes, tags: ['kubernetes']}
    - role: geerlingguy.helm
