
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Link global gitignore file
  file:
    src: "{{ dotfiles_home }}/ansible/roles/git/files/gitignore_global.link"
    dest: "~/.gitignore_global"
    state: link
    force: yes

- name: Check if gitconfig exists
  stat: path="~/.gitconfig"
  register: gitconfig_stat

- name: Back up gitconfig
  command: mv ~/.gitconfig ~/.gitconfig.bak
  args:
    creates: "~/.gitconfig.bak"
  when: gitconfig_stat.stat.exists

- name: Make sure gitconfig is up to date
  template:
    src: "gitconfig.j2"
    dest: "~/.gitconfig"
