
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "~/.tmux/plugins/tpm"

- name: Symlink .tmux.conf
  file:
    src: "{{ dotfiles_home }}/ansible/roles/tmux/files/tmux.conf"
    dest: "~/.tmux.conf"
    state: link
  when: ansible_os_family != "Debian"

# TODO: macOS
# On macOS, use the same tmux.conf, but also use
# reattach_to_user_namespace (for clipboard support)
#- name: Symlink .tmux.conf (macOS)
#  file:
#    src: "{{ dotfiles_home }}/ansible/roles/tmux/files/tmux-mac.conf"
#    dest: "~/.tmux.conf"
#    state: link
#  when: ansible_os_family == "Darwin"
