# Installation
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"

#- name: Install python-language-server (used by ale) with pipx
#  command: "pipx install --force python-language-server"
#  args:
#    creates: "~/.local/pipx/venvs/python-language-server"
#  tags:
#    - pipx

# Plugin manager
- name: Makes sure autoload directory exists
  file: path="~/.vim/autoload" state=directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "~/.vim/autoload/plug.vim"

## Snippets
#- name: Makes sure UltiSnips directory exists
#  file: path="~/.vim/UltiSnips" state=directory
#
#- name: Symlink all snippet files
#  file:
#    src: "{{ dotfiles_home }}/ansible/roles/vim/files/{{item}}"
#    dest: "{{ dotfiles_user_home}}/.vim/UltiSnips/{{item}}"
#    state: link
#  with_items:
#    - "python.snippets"
#    - "rst.snippets"
#    - "javascript.snippets"

# Configuration
- name: Check if vimrc exists
  stat: path="~/.vimrc"
  register: vimrc_stat
  failed_when: False

- name: Backup vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "~/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: Symlink vimrc
  file:
    src: "{{ dotfiles_home }}/ansible/roles/vim/files/vimrc"
    dest: "~/.vimrc"
    state: link

- name: Install plugins
  command: vim +PlugInstall +qall
  when: vim_install_plugins|bool
